import { defineConfig } from "orval";

export default defineConfig({
  playsayApi: {
    input: {
      target: "../../contracts/openapi.yaml",
    },
    output: {
      target: "src/generated/playsay-api.ts",
      client: "fetch",
      baseUrl: "/api",
      prettier: false,
      clean: true,
      override: {
        header: (info) => [
          "Generated by Orval.",
          "Do not edit manually.",
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
        fetch: {
          includeHttpResponseReturnType: true,
        },
      },
    },
  },
  registrationApi: {
    input: {
      target: "../../contracts/registration-openapi.yaml",
    },
    output: {
      target: "src/generated/registration-api.ts",
      client: "fetch",
      baseUrl: "/api",
      prettier: false,
      clean: false,
      override: {
        header: (info) => [
          "Generated by Orval.",
          "Do not edit manually.",
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
        fetch: {
          includeHttpResponseReturnType: true,
        },
      },
    },
  },
  vocabularyApi: {
    input: {
      target: "../../contracts/vocabulary-openapi.yaml",
    },
    output: {
      target: "src/generated/vocabulary-api.ts",
      client: "fetch",
      baseUrl: "",
      prettier: false,
      clean: false,
      override: {
        header: (info) => [
          "Generated by Orval.",
          "Do not edit manually.",
          ...(info.title ? [info.title] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
        fetch: {
          includeHttpResponseReturnType: true,
        },
      },
    },
  },
});
