// Generated by scripts/contracts/generate-worksheet-import-client.mjs from the service-owned OpenAPI contract.
// Do not edit by hand.
package com.playsay.gateway.client

import com.fasterxml.jackson.databind.JsonNode
import com.playsay.contract.worksheetimport.model.WorksheetMaterializationBundle
import com.playsay.gateway.dto.WorksheetImportCreateRequest
import java.util.UUID
import org.springframework.web.multipart.MultipartFile

data class WorksheetImportClientContent(val bytes: ByteArray, val contentType: String)

interface WorksheetImportInternalClient {
    fun create(request: WorksheetImportCreateRequest, files: List<MultipartFile>, userBearerToken: String): JsonNode
    fun get(sessionId: UUID, userBearerToken: String): JsonNode
    fun cancel(sessionId: UUID, userBearerToken: String)
    fun preview(sessionId: UUID, pageId: UUID, userBearerToken: String): WorksheetImportClientContent
    fun replaceReview(sessionId: UUID, revision: Long, review: JsonNode, userBearerToken: String): JsonNode
    fun continueManually(sessionId: UUID, userBearerToken: String): JsonNode
    fun retryAnalysis(sessionId: UUID, userBearerToken: String): JsonNode
    fun materializationBundle(sessionId: UUID, revision: Long, rightsConfirmed: Boolean, userBearerToken: String): WorksheetMaterializationBundle
    fun materializationAsset(sessionId: UUID, revision: Long, assetId: UUID, userBearerToken: String): ByteArray
    fun acknowledgeMaterialization(sessionId: UUID, revision: Long, materialId: UUID, userBearerToken: String)
}
