server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${PLAYSAY_AUTH_ISSUER_URI:https://ops.play-and-say.ru:18443/keycloak/realms/playsay}
          jwk-set-uri: ${PLAYSAY_AUTH_JWK_SET_URI:https://ops.play-and-say.ru:18443/keycloak/realms/playsay/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
