package com.playsay.gateway.utils

object MetaData {
    object Roles {
        const val ADMIN = "ADMIN"
        const val TEACHER = "TEACHER"
        const val STUDENT = "STUDENT"
    }

    object Authorities {
        const val PREFIX = "ROLE_"
        const val ADMIN = "${PREFIX}${Roles.ADMIN}"
        const val TEACHER = "${PREFIX}${Roles.TEACHER}"
        const val STUDENT = "${PREFIX}${Roles.STUDENT}"
    }

    object LessonStatuses {
        const val SCHEDULED = "SCHEDULED"
        const val IN_PROGRESS = "IN_PROGRESS"
        const val COMPLETED = "COMPLETED"
        const val CANCELLED = "CANCELLED"
    }

    object LessonTypes {
        const val INDIVIDUAL = "INDIVIDUAL"
        const val GROUP = "GROUP"
    }

    object LessonWorkModes {
        const val SHARED = "SHARED"
        const val PARALLEL = "PARALLEL"
    }

    object LessonRecurrenceModes {
        const val WEEKLY_COUNT = "WEEKLY_COUNT"
        const val WEEKLY_BY_WEEK = "WEEKLY_BY_WEEK"
    }

    object LessonReminderTypes {
        const val LESSON_START_30M = "LESSON_START_30M"
    }

    object LessonReminderRecipientRoles {
        const val TEACHER = "TEACHER"
        const val STUDENT = "STUDENT"
    }

    object LessonReminderStatuses {
        const val PENDING = "PENDING"
        const val SENT = "SENT"
        const val FAILED = "FAILED"
        const val SKIPPED = "SKIPPED"
        const val CANCELLED = "CANCELLED"
    }

    object AttendanceStatuses {
        const val PLANNED = "PLANNED"
        const val PRESENT = "PRESENT"
    }

    object MaterialVisibility {
        const val PRIVATE = "PRIVATE"
        const val PUBLIC = "PUBLIC"
    }

    object MaterialStatuses {
        const val DRAFT = "DRAFT"
        const val PUBLISHED = "PUBLISHED"
        const val ARCHIVED = "ARCHIVED"
    }

    object CollaborationScopes {
        const val INDIVIDUAL = "INDIVIDUAL"
        const val GROUP = "GROUP"
    }

    object AssignmentTypes {
        const val MATERIAL_WORK = "MATERIAL_WORK"
        const val HOMEWORK = "HOMEWORK"
    }

    object AssignmentStatuses {
        const val ACTIVE = "ACTIVE"
        const val ARCHIVED = "ARCHIVED"
    }

    object AiProviders {
        const val STUB = "stub"
        const val OPENAI = "openai"
    }

    object StorageProviders {
        const val MEMORY = "memory"
        const val S3 = "s3"
    }

    object RealtimeMessageTypes {
        const val ERROR = "error"
        const val LESSON_UPDATED = "lesson.updated"
        const val LESSON_DELETED = "lesson.deleted"
    }

    object ErrorCodes {
        const val ADMIN_ROLE_REQUIRED = "ADMIN_ROLE_REQUIRED"
        const val TEACHER_OR_ADMIN_ROLE_REQUIRED = "TEACHER_OR_ADMIN_ROLE_REQUIRED"
        const val COURSE_NOT_FOUND = "COURSE_NOT_FOUND"
        const val COURSE_LESSON_NOT_FOUND = "COURSE_LESSON_NOT_FOUND"
        const val SCHEDULED_LESSON_NOT_FOUND = "SCHEDULED_LESSON_NOT_FOUND"
        const val SCHEDULED_LESSON_CANNOT_START = "SCHEDULED_LESSON_CANNOT_START"
        const val UNKNOWN_PARTICIPANT_SUBJECT = "UNKNOWN_PARTICIPANT_SUBJECT"
        const val LESSON_TEMPLATE_ID_NOT_FOUND = "LESSON_TEMPLATE_ID_NOT_FOUND"
        const val MATERIAL_ID_NOT_FOUND = "MATERIAL_ID_NOT_FOUND"
        const val SCHEDULED_END_BEFORE_START = "SCHEDULED_END_BEFORE_START"
        const val UNSUPPORTED_LESSON_STATUS = "UNSUPPORTED_LESSON_STATUS"
        const val UNSUPPORTED_LESSON_TYPE = "UNSUPPORTED_LESSON_TYPE"
        const val UNSUPPORTED_LESSON_WORK_MODE = "UNSUPPORTED_LESSON_WORK_MODE"
        const val UNSUPPORTED_LESSON_RECURRENCE = "UNSUPPORTED_LESSON_RECURRENCE"
        const val LESSON_RECURRENCE_COUNT_OUT_OF_RANGE = "LESSON_RECURRENCE_COUNT_OUT_OF_RANGE"
        const val LESSON_RECURRENCE_WEEKDAY_INVALID = "LESSON_RECURRENCE_WEEKDAY_INVALID"
        const val LESSON_RECURRENCE_TIME_ZONE_INVALID = "LESSON_RECURRENCE_TIME_ZONE_INVALID"
        const val ORDER_INDEX_NEGATIVE = "ORDER_INDEX_NEGATIVE"
        const val PLANNED_DURATION_OUT_OF_RANGE = "PLANNED_DURATION_OUT_OF_RANGE"
        const val MATERIAL_NOT_FOUND = "MATERIAL_NOT_FOUND"
        const val MATERIAL_EDIT_FORBIDDEN = "MATERIAL_EDIT_FORBIDDEN"
        const val MATERIAL_ARCHIVE_FORBIDDEN = "MATERIAL_ARCHIVE_FORBIDDEN"
        const val MATERIAL_IMAGES_FORBIDDEN = "MATERIAL_IMAGES_FORBIDDEN"
        const val MATERIAL_ANSWER_SUGGESTIONS_FORBIDDEN = "MATERIAL_ANSWER_SUGGESTIONS_FORBIDDEN"
        const val MATERIAL_ANSWER_ITEMS_NOT_FOUND = "MATERIAL_ANSWER_ITEMS_NOT_FOUND"
        const val MATERIAL_ASSET_NOT_FOUND = "MATERIAL_ASSET_NOT_FOUND"
        const val MATERIAL_ASSET_CONTENT_NOT_FOUND = "MATERIAL_ASSET_CONTENT_NOT_FOUND"
        const val MATERIAL_ASSET_STORAGE_FAILED = "MATERIAL_ASSET_STORAGE_FAILED"
        const val MATERIAL_ASSET_EDIT_FORBIDDEN = "MATERIAL_ASSET_EDIT_FORBIDDEN"
        const val MATERIAL_IMAGE_PAGE_UNSUPPORTED_TYPE = "MATERIAL_IMAGE_PAGE_UNSUPPORTED_TYPE"
        const val MATERIAL_IMAGE_PAGE_TOO_LARGE = "MATERIAL_IMAGE_PAGE_TOO_LARGE"
        const val MATERIAL_IMAGE_PAGE_UNSAFE_SVG = "MATERIAL_IMAGE_PAGE_UNSAFE_SVG"
        const val MATERIAL_IMAGE_PAGE_PARALLEL_UNSUPPORTED = "MATERIAL_IMAGE_PAGE_PARALLEL_UNSUPPORTED"
        const val UNSUPPORTED_CEFR_LEVEL = "UNSUPPORTED_CEFR_LEVEL"
        const val UNSUPPORTED_MATERIAL_VISIBILITY = "UNSUPPORTED_MATERIAL_VISIBILITY"
        const val UNSUPPORTED_MATERIAL_STATUS = "UNSUPPORTED_MATERIAL_STATUS"
        const val FIELD_REQUIRED = "FIELD_REQUIRED"
        const val FIELD_TOO_LONG = "FIELD_TOO_LONG"
        const val IMAGE_DATA_URL_INVALID_TYPE = "IMAGE_DATA_URL_INVALID_TYPE"
        const val FIELD_EMPTY = "FIELD_EMPTY"
        const val IMAGE_DATA_URL_INVALID_BASE64 = "IMAGE_DATA_URL_INVALID_BASE64"
        const val JSON_FIELD_TOO_LARGE = "JSON_FIELD_TOO_LARGE"
        const val INVALID_COUNTRY_CODE = "INVALID_COUNTRY_CODE"
        const val INVALID_BIRTH_DATE = "INVALID_BIRTH_DATE"
        const val VIDEO_PLAYBACK_SESSION_NOT_FOUND = "VIDEO_PLAYBACK_SESSION_NOT_FOUND"
        const val YOUTUBE_RELAY_UNAVAILABLE = "YOUTUBE_RELAY_UNAVAILABLE"
        const val PAYMENT_ADMIN_ROLE_REQUIRED = "PAYMENT_ADMIN_ROLE_REQUIRED"
        const val PAYMENT_INVOICE_NOT_FOUND = "PAYMENT_INVOICE_NOT_FOUND"
        const val PAYMENT_SERVICE_UNAVAILABLE = "PAYMENT_SERVICE_UNAVAILABLE"
        const val REGISTRATION_SERVICE_UNAVAILABLE = "REGISTRATION_SERVICE_UNAVAILABLE"
        const val MANAGED_STUDENT_IDENTITY_CONFLICT = "MANAGED_STUDENT_IDENTITY_CONFLICT"
        const val EMAIL_SERVICE_UNAVAILABLE = "EMAIL_SERVICE_UNAVAILABLE"
        const val LIVEKIT_NOT_CONFIGURED = "LIVEKIT_NOT_CONFIGURED"
        const val LIVEKIT_WEBHOOK_SIGNATURE_MISSING = "LIVEKIT_WEBHOOK_SIGNATURE_MISSING"
        const val LIVEKIT_WEBHOOK_SIGNATURE_INVALID = "LIVEKIT_WEBHOOK_SIGNATURE_INVALID"
        const val LIVEKIT_WEBHOOK_ISSUER_INVALID = "LIVEKIT_WEBHOOK_ISSUER_INVALID"
        const val LIVEKIT_WEBHOOK_SIGNATURE_EXPIRED = "LIVEKIT_WEBHOOK_SIGNATURE_EXPIRED"
        const val LIVEKIT_WEBHOOK_PAYLOAD_HASH_MISSING = "LIVEKIT_WEBHOOK_PAYLOAD_HASH_MISSING"
        const val LIVEKIT_WEBHOOK_PAYLOAD_HASH_INVALID = "LIVEKIT_WEBHOOK_PAYLOAD_HASH_INVALID"
        const val COLLABORATION_DOCUMENT_NOT_FOUND = "COLLABORATION_DOCUMENT_NOT_FOUND"
        const val COLLABORATION_ACCESS_DENIED = "COLLABORATION_ACCESS_DENIED"
        const val COLLABORATION_SCOPE_INVALID = "COLLABORATION_SCOPE_INVALID"
        const val COLLABORATION_SNAPSHOT_INVALID = "COLLABORATION_SNAPSHOT_INVALID"
        const val COLLABORATION_NOT_CONFIGURED = "COLLABORATION_NOT_CONFIGURED"
        const val ASSIGNMENT_NOT_FOUND = "ASSIGNMENT_NOT_FOUND"
        const val ASSIGNMENT_ACCESS_DENIED = "ASSIGNMENT_ACCESS_DENIED"
        const val ASSIGNMENT_RECIPIENTS_REQUIRED = "ASSIGNMENT_RECIPIENTS_REQUIRED"
        const val EXTERNAL_URL_REDIRECT_LOCATION_MISSING = "EXTERNAL_URL_REDIRECT_LOCATION_MISSING"
        const val EXTERNAL_URL_TOO_MANY_REDIRECTS = "EXTERNAL_URL_TOO_MANY_REDIRECTS"
        const val EXTERNAL_URL_HTTP_ERROR = "EXTERNAL_URL_HTTP_ERROR"
        const val EXTERNAL_URL_UNREADABLE_CONTENT_TYPE = "EXTERNAL_URL_UNREADABLE_CONTENT_TYPE"
        const val EXTERNAL_URL_NOT_ENOUGH_TEXT = "EXTERNAL_URL_NOT_ENOUGH_TEXT"
        const val EXTERNAL_URL_READ_FAILED = "EXTERNAL_URL_READ_FAILED"
        const val EXTERNAL_URL_INVALID = "EXTERNAL_URL_INVALID"
        const val EXTERNAL_URL_UNSUPPORTED_SCHEME = "EXTERNAL_URL_UNSUPPORTED_SCHEME"
        const val EXTERNAL_URL_HOST_INVALID = "EXTERNAL_URL_HOST_INVALID"
        const val EXTERNAL_URL_HOST_NOT_ALLOWED = "EXTERNAL_URL_HOST_NOT_ALLOWED"
        const val EXTERNAL_URL_HOST_UNRESOLVED = "EXTERNAL_URL_HOST_UNRESOLVED"
        const val EXTERNAL_URL_CONTENT_TOO_LARGE = "EXTERNAL_URL_CONTENT_TOO_LARGE"
        const val AI_PROVIDER_UNKNOWN = "AI_PROVIDER_UNKNOWN"
        const val AI_API_KEY_NOT_CONFIGURED = "AI_API_KEY_NOT_CONFIGURED"
        const val AI_MATERIAL_GENERATION_FAILED = "AI_MATERIAL_GENERATION_FAILED"
        const val AI_MATERIAL_RESPONSE_MISSING = "AI_MATERIAL_RESPONSE_MISSING"
        const val AI_MATERIAL_SCHEMA_INVALID = "AI_MATERIAL_SCHEMA_INVALID"
        const val AI_RESPONSE_INVALID_JSON = "AI_RESPONSE_INVALID_JSON"
        const val AI_GENERATED_MATERIAL_TITLE_INVALID = "AI_GENERATED_MATERIAL_TITLE_INVALID"
        const val AI_GENERATED_MATERIAL_METADATA_INVALID = "AI_GENERATED_MATERIAL_METADATA_INVALID"
        const val AI_GENERATED_MATERIAL_DOCUMENT_INVALID = "AI_GENERATED_MATERIAL_DOCUMENT_INVALID"
        const val AI_GENERATED_MATERIAL_RUBRIC_INVALID = "AI_GENERATED_MATERIAL_RUBRIC_INVALID"
        const val AI_GENERATED_MATERIAL_PAGE_EMPTY = "AI_GENERATED_MATERIAL_PAGE_EMPTY"
        const val AI_GENERATED_MATERIAL_BLOCK_UNSUPPORTED = "AI_GENERATED_MATERIAL_BLOCK_UNSUPPORTED"
        const val AI_IMAGE_GENERATION_FAILED = "AI_IMAGE_GENERATION_FAILED"
        const val AI_IMAGE_RESPONSE_MISSING_DATA = "AI_IMAGE_RESPONSE_MISSING_DATA"
        const val AI_IMAGE_RESPONSE_MISSING_BYTES = "AI_IMAGE_RESPONSE_MISSING_BYTES"
        const val AI_ANSWER_SUGGESTION_PROVIDER_UNKNOWN = "AI_ANSWER_SUGGESTION_PROVIDER_UNKNOWN"
        const val AI_ANSWER_SUGGESTION_FAILED = "AI_ANSWER_SUGGESTION_FAILED"
        const val AI_ANSWER_SUGGESTIONS_MISSING = "AI_ANSWER_SUGGESTIONS_MISSING"
        const val AI_ANSWER_SUGGESTION_SCHEMA_INVALID = "AI_ANSWER_SUGGESTION_SCHEMA_INVALID"
        const val INVALID_REQUEST = "INVALID_REQUEST"
    }

    object Messages {
        const val MATERIAL_DRAFT_DESCRIPTION = "MATERIAL_DRAFT_DESCRIPTION"
        const val MATERIAL_GOAL_TITLE = "MATERIAL_GOAL_TITLE"
        const val FLASHCARD_TOPIC_TRANSLATION = "FLASHCARD_TOPIC_TRANSLATION"
        const val FLASHCARD_OPINION_TRANSLATION = "FLASHCARD_OPINION_TRANSLATION"
        const val FLASHCARD_BECAUSE_TRANSLATION = "FLASHCARD_BECAUSE_TRANSLATION"
        const val RUBRIC_TASK_COMPLETION = "RUBRIC_TASK_COMPLETION"
        const val RUBRIC_GRAMMAR = "RUBRIC_GRAMMAR"
        const val RUBRIC_VOCABULARY = "RUBRIC_VOCABULARY"
        const val RUBRIC_FLUENCY = "RUBRIC_FLUENCY"
        const val MATERIAL_NEW_TITLE = "MATERIAL_NEW_TITLE"
        const val MATERIAL_IMPORT_URL_PROMPT = "MATERIAL_IMPORT_URL_PROMPT"
        const val MATERIAL_FROM_URL_TITLE = "MATERIAL_FROM_URL_TITLE"
        const val MATERIAL_AI_IMAGE_ALT = "MATERIAL_AI_IMAGE_ALT"
        const val MATERIAL_STATIC_IMAGE_PAGE_TITLE = "MATERIAL_STATIC_IMAGE_PAGE_TITLE"
        const val MATERIAL_NEW_BLOCK_TITLE = "MATERIAL_NEW_BLOCK_TITLE"
        const val MATERIAL_NEW_BLOCK_BODY = "MATERIAL_NEW_BLOCK_BODY"
    }
}
